/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cce8ba3e-09dd-4eb8-be97-d3ccc0ef3754",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SglU9NgnQ",
    "aws_user_pools_web_client_id": "43nbp301msumki442fmh74l4s3",
    "oauth": {
        "domain": "98yvc1f8u558-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost/",
        "redirectSignOut": "https://localhost/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
