/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2b8eee6c-2264-4fdf-8611-58eb1b7f56fd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DBMiDwn5J",
    "aws_user_pools_web_client_id": "6vhnvu596avaai1ukom20ko6mb",
    "oauth": {
        "domain": "webclientappsynctest615c2a5b-615c2a5b-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:30000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
